### ISSUE TITLE
[Feature] Allow HTTP sites

### ISSUE THREAD

**Issue by esteblock** [Creit-Tech/xBull-Wallet-Connect#2]
I would be great to have to have in Settings something like "Allow non HTTPS connections"
Why? Some users want to try sites in localhost without the need of setting a reverse proxy

**Comment by earrietadev** [comment]
Hi @esteblock, this library can't change the behavior of xBull Wallet so the ticket is better if it was on xBull's own repository, the non-https connection restriction is only for the extension version of the wallet.

I can add localhost as a whitelisted option instead of just giving full support to non-http pages. I just created the ticket so it gets includes in the next update https://github.com/Creit-Tech/xBull-Wallet/issues/12

But if you want to test in localhost in the meantime without setting up an HTTPS connection then you can use the progressive web app (PWA) version of the wallet hosted at https://wallet.xbull.app which this library uses automatically if you want to connect with an unsecured website connection.

**Comment by earrietadev** [comment]
Closing this as it was added to the latest xBull Wallet's version: https://github.com/Creit-Tech/xBull-Wallet/commit/a6e2807e5348a28215991f4ea0fed746ba1d2365
